production:
  adapter: sqlite3
  database: db/license_to_kill_production.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/license_to_kill_test.sqlite3
  pool: 5
  timeout: 5000
